env:
  global:
    - REGISTRY_USER=slyu
matrix:
  include:
  - sudo: required
    services:
        - docker
    env:
        - NODE_ENV=test
    before_script:
        - sudo docker pull olinfse/goober || true
        - env > .env
        - echo .env
    script:
        - sudo docker build --pull --cache-from olinfse/goober --tag olinfse/goober .
        - mkdir ~/data
        - sudo docker run -d -p 27017:27017 -v ~/data:/data/db --name mongodb dockerfile/mongodb
        - sudo docker ps -a
        - sudo docker run --env-file .env --link mongodb -d -p 8080:8080 olinfse/goober
        - sudo docker run olinfse/goober /bin/bash -c "npm run test"
    after_script:
        - docker images
    before_deploy:
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
    deploy:
        provider: script
        script: docker push olinfse/goober
        on:
            branch: dev

  - language: node_js
    node_js:
    - lts/*
    services:
    - mongodb
    dist: trusty
    sudo: required
    addons:
    - chrome: stable
    env:
    - NODE_ENV=test
    before_install:
    - npm install
    - npm run server
    - export CHROME_BIN=/usr/bin/google-chrome
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sudo apt-get update
    - sudo apt-get install -y libappindicator1 fonts-liberation
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - sudo dpkg -i google-chrome*.deb
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
      &
    install:
    - cd frontend
    - npm install
    script:
    - npm run e2e
