matrix:
  include:
    # backend jest tests
    - language: node_js
      node_js:
          - "lts/*"
      services:
          - mongodb
      env:
        - NODE_ENV=test
      install:
        - npm install
      script:
        - npm test

    # e2e tests
    - language: node_js
      node_js:
          - "lts/*"
      services:
          - mongodb
      sudo: required
      addons:
        - chrome: beta
      env:
        - NODE_ENV=test

      before_install:
        - npm install
        - npm run server
        - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
      install:
        - cd frontend
        - npm install
      script:
        - npm run e2e
