env:
  global:
    - REGISTRY_USER=slyu
    - MONGODB_URI=mongodb://mongo:27017
    - DOCKER_COMPOSE_VERSION=1.20.1
matrix:
  include:
  - sudo: required
    language: node_js
    services:
        - docker
    env:
        - NODE_ENV=test
    addons:
    - chrome: stable
    before_install:
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
        - export CHROME_BIN=/usr/bin/google-chrome
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sudo apt-get update
        - sudo apt-get install -y libappindicator1 fonts-liberation
        - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        - sudo dpkg -i google-chrome*.deb
        - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
          &
    before_script:
        - env > .env.list
    install: true
    script:
        - sudo docker-compose up --detach
        - sudo docker-compose run goober /bin/bash -c "npm run test"
        - sudo docker-compose run goober /bin/bash -c "cd frontend;npm run e2e"
    after_script:
        - docker images
    before_deploy:
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
    deploy:
        provider: script
        script: docker push olinfse/goober
        on:
            branch: seungin/docker_setup


