version: '3'

services:
    mongo:
        image: 'mongo:3.4.1'
        ports:
            - '27017:27017'
        volumes:
            - 'mongo:/data/db'
    selenium:
        image: 'selenium/standalone-chrome'
        expose:
            - '4444'
    goober:
        tty: true
        stdin_open: true
        depends_on:
            - 'mongo'
        build: .
        command: node server.js
        ports:
            - '8080:8080'
        env_file:
            - .env.list
        links:
            - selenium
        environment:
            - MONGODB_URI=mongodb://mongo:27017/
volumes:
    mongo:
