version: '3'

services:
    mongo:
        image: 'mongo:3.4.1'
        ports:
            - '27017:27017'
        volumes:
            - 'mongo:/data/db'
        networks:
            - gooberplatform
    chromedriver:
        image: robcherry/docker-chromedriver:latest
        environment:
            CHROMEDRIVER_WHITELISTED_IPS: ""
        networks:
            - gooberplatform
    goober:
        tty: true
        stdin_open: true
        depends_on:
            - 'mongo'
            - 'chromedriver'
        build: .
        command: node server.js
        ports:
            - '8080:8080'
        env_file:
            - .env.list
        environment:
            - MONGODB_URI=mongodb://mongo:27017/
        networks:
            - gooberplatform
volumes:
    mongo:
networks:
    gooberplatform:
        driver: bridge
