version: '3.6'
services:
    mongo:
        image: 'mongo:3.4.1'
        ports:
            - '27017:27017'
        volumes:
            - 'mongo:/data/db'
    chrome:
        image: 'selenium/node-chrome:3.11.0-californium'
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - hub
        environment:
            HUB_HOST: hub
    hub:
        image: 'selenium/hub:3.11.0-californium'
        ports:
            - "4444:4444"
    goober:
        tty: true
        stdin_open: true
        depends_on:
            - 'mongo'
        build:
            context: .
            cache_from:
                - olinfse/goober:latest
        command: node server.js
        ports:
            - '8080:8080'
        env_file:
            - .env.list
        links:
            - hub
        environment:
            - MONGODB_URI=mongodb://mongo:27017/
volumes:
    mongo:
